name: tests
on: push
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Java
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9.4'

      - name: Setup Clojure tools
        uses: DeLaGuardo/setup-clojure@master
        with:
          tools-deps: 1.11.1.1155

      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Cache m2
        uses: actions/cache@v2
        with:
          path: ~/.m2
          key: m2-${{ hashFiles('deps.edn') }}

      - name: Cache gitlibs
        uses: actions/cache@v2
        with:
          path: ~/.gitlibs
          key: gitlibs-${{ hashFiles('deps.edn') }}

      - name: Cache pip
        uses: actions/cache@v2
        with:
          path: ~/.cache/pip # This path is specific to Ubuntu
          key: pip-${{ hashFiles('requirements.txt', 'requirements-sppl.txt') }}

      - name: Prepare Clojure dependencies
        run: clojure -A:test -P

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --no-deps "$(cat requirements-sppl.txt)"

      - name: Run tests
        run: clojure -M:test
